language: php

php:
  - 7.0
  - nightly
  - hhvm

branches:
  except:
    - development

matrix:
  allow_failures:
    - php: hhvm

before_script:
  - composer install --dev -o

script:
  - ./vendor/bin/phpunit

addons:
    code_climate:
        repo_token: 0193795486bd1bcfc90b116b7447216cb08c1f6c8761787b6f45f169469643de