# Banco de dados
database:
  production:
    driver: pdo_sqlite
    database: skel
    dbname: skel
    path: tmp/skel-production.sqlite

  development:
    driver: pdo_sqlite
    database: skel
    dbname: skel
    path: tmp/skel-development.sqlite

  testing:
    driver: pdo_sqlite
    database: skel
    dbname: skel
    path: tmp/skel-testing.sqlite