# Banco de dados
database:
  production:
    driver: pdo_pgsql
    host: ec2-50-19-239-232.compute-1.amazonaws.com
    database: d9eot47ulp5kgm
    user: ebyggwqepoxqpx
    port: 5432
#    path: tmp/twitter-like-production.sqlite

  development:
    driver: pdo_sqlite
    database: twitter-like-development
    dbname: twitter-like
    path: tmp/twitter-like-development.sqlite

  testing:
    driver: pdo_sqlite
    database: twitter-like-test
    dbname: twitter-like
    path: tmp/twitter-like-testing.sqlite