# Banco de dados
database:
  production:
    driver: pdo_pgsql
    database: twitter-like-production
    user: postgres

  development:
    driver: pdo_sqlite
    database: twitter-like-development
    dbname: twitter-like
    path: tmp/twitter-like-development.sqlite

  testing:
    driver: pdo_sqlite
    database: twitter-like-test
    dbname: twitter-like
    path: tmp/twitter-like-testing.sqlite